language: node_js
node_js:
 - "4"
 - "6"
services:
 - couchdb
install:
 - npm install
script:
 - npm run linter
 - npm run test
 - node examples/example.js
 - node examples/view.js
 - node examples/simple.js
 - node examples/attachment.js
 - node examples/attachment-stream.js
 - node examples/attachment-stream2.js
 - node examples/update-handler.js
